import { Project, Experience, Contribution, Skill } from './types';

export const projects: Project[] = [
  {
    slug: 'devflow',
    title: 'DevFlow',
    description: 'A real-time collaborative code review platform with inline comments, threaded discussions, and CI/CD integration.',
    longDescription: 'DevFlow reimagines code review by making it feel as natural as pair programming. Built with Next.js and WebSockets, it supports live cursors, inline annotations, and hooks directly into GitHub Actions pipelines.',
    tags: ['Next.js', 'TypeScript', 'WebSockets', 'PostgreSQL'],
    liveUrl: 'https://devflow.example.com',
    repoUrl: 'https://github.com/you/devflow',
    featured: true,
    year: '2024',
  },
  {
    slug: 'nomad-desk',
    title: 'Nomad Desk',
    description: 'A curated directory of remote-friendly co-working spaces worldwide with booking, reviews, and amenity filters.',
    longDescription: 'Nomad Desk solves the "where do I work today?" problem for digital nomads. Features include map-based search, verified reviews, amenity filtering (WiFi speed, power outlets, coffee quality), and a lightweight booking layer.',
    tags: ['React', 'Node.js', 'MongoDB', 'MapBox'],
    liveUrl: 'https://nomaddesk.example.com',
    year: '2024',
  },
  {
    slug: 'pulse-analytics',
    title: 'Pulse Analytics',
    description: 'Lightweight, privacy-first website analytics dashboard. No cookies, no GDPR headaches.',
    longDescription: 'Pulse is a drop-in alternative to Google Analytics that uses cookieless fingerprinting and edge functions to deliver real-time traffic insights with zero personal data collection.',
    tags: ['Next.js', 'Vercel Edge', 'ClickHouse', 'TypeScript'],
    repoUrl: 'https://github.com/you/pulse',
    featured: true,
    year: '2023',
  },
  {
    slug: 'inktype',
    title: 'InkType',
    description: 'A minimalist markdown editor with focus mode, custom themes, and one-click publishing to Ghost/Notion.',
    tags: ['Electron', 'React', 'TypeScript', 'Ghost API'],
    liveUrl: 'https://inktype.example.com',
    year: '2023',
  },
];

export const experiences: Experience[] = [
  {
    slug: 't-global',
    company: 'Tactology Global',
    logo: '/company/tg.png',
    role: 'Frontend Engineer',
    period: 'March 2026 — Present',
    workMode: 'Remote',
    shortDescription: 'Leading the design system team and modernising a legacy React codebase to Next.js App Router.',
    longDescription: 'We are Tactologyglobal, We Are Willing to Provide The Best Service For You. Established in 2020, Tactologyglobal comprises a dedicated team of both on-site and remote members, all poised to transform clients visions into tangible matters. We pride ourselves on our proven track record and client successes.',
    tech: ['Next.js', 'TypeScript', 'Storybook', 'Figma', 'GraphQL'],
    highlights: [
      'Reduced initial load time by 38% via code-splitting and image optimisation',
      'Built and shipped a 60-component design system adopted across 4 product teams',
      'Introduced E2E testing with Playwright — coverage went from 0% to 72%',
    ],
  },
  {
    slug: 'codeweb-project-solutions',
    company: 'Codeweb Project Solutions',
    logo: '/company/cd.jpg',
    role: 'Senior Frontend Engineer',
    period: 'Sept 2024 — Present',
    workMode: 'Remote',
    shortDescription: 'Leading the design system team and modernising a legacy React codebase to Next.js App Router.',
    longDescription: 'At Acme Corp I own the frontend architecture for the core SaaS platform serving 40k+ users. I introduced a typed component library, reduced bundle size by 38%, and mentored two junior engineers through their first major feature launches.',
    tech: ['React.js', 'TypeScript', 'Figma', 'Rest API'],
    highlights: [
      'Crafted responsive web applications that boosted user engagement by 30%',
      'Optimized front-end performance, reducing load times by 50% on key projects',
      'Implemented modern frameworks, increasing development speed by 40%',
    ],
  },
  {
    slug: 'gapplus-limited',
    company: 'GAPPLUS Limited',
    logo: '/company/gp.png',
    role: 'Senior Frontend Developer',
    period: 'Jun 2021 — Dec 2022',
    workMode: 'Hybrid',
    shortDescription: 'Built microservices and customer-facing features for a fintech startup processing $2M+ daily.',
    longDescription: 'Bright Labs was my first proper startup experience. I shipped features end-to-end — from database schema design to polished UI — and helped scale the backend to handle a 10× traffic spike during a product launch.',
    tech: ['React', 'Node.js', 'PostgreSQL', 'Redis', 'AWS'],
    highlights: [
      'Optimized site performance, reducing load times by 50% for better UX',
      'Crafted responsive web designs that boosted user engagement by 30%',
      'Maintained high coding standards, resulting in a 20% decrease in bugs',
    ],
  },
  {
    slug: 'boakye-digital',
    company: 'Boakye Digital',
    logo: '/company/bd.png',
    role: 'Web Developer Lead',
    period: 'Jan 2025 — June 2025',
    workMode: 'Remote',
    shortDescription: 'Delivered 10+ client projects across e-commerce, SaaS, and marketing verticals.',
    tech: ['React', 'Vue', 'WordPress', 'Tailwind', 'Shopify'],
    highlights: [
      'Enhanced user experience, resulting in a 25% increase in customer retention.',
      'Presented innovative solutions that increased client satisfaction by 35%.',
    ],
  },
];

export const contributions: Contribution[] = [
  {
    slug: 'next-contribution',
    project: 'Next.js',
    description: 'Fixed a hydration mismatch bug in the App Router when using dynamic imports with Suspense boundaries.',
    url: 'https://github.com/vercel/next.js/pull/00000',
    type: 'Bug Fix',
    tags: ['Next.js', 'React'],
    year: '2024',
  },
  {
    slug: 'tailwind-docs',
    project: 'Tailwind CSS',
    description: 'Improved the v4 migration guide with clearer examples for custom plugin authoring.',
    url: 'https://github.com/tailwindlabs/tailwindcss.com/pull/00000',
    type: 'Docs',
    tags: ['Tailwind CSS', 'Documentation'],
    year: '2024',
  },
  {
    slug: 'react-hook-form',
    project: 'React Hook Form',
    description: 'Added TypeScript generics support to the useFieldArray hook for strongly-typed nested forms.',
    url: 'https://github.com/react-hook-form/react-hook-form/pull/00000',
    type: 'Feature',
    tags: ['TypeScript', 'React'],
    year: '2023',
  },
  {
    slug: 'radix-ui',
    project: 'Radix UI',
    description: 'Contributed accessibility improvements to the Dialog component — focus trap now respects dynamically added focusable elements.',
    url: 'https://github.com/radix-ui/primitives/pull/00000',
    type: 'Feature',
    tags: ['Accessibility', 'React'],
    year: '2023',
  },
];

export const skills: Skill[] = [
  { name: 'Next.js', shortDescription: 'App Router, SSR, ISR, edge functions, API routes.', proficiency: 5, category: 'Frontend', logo: '/Next.js.svg' },
  { name: 'React', shortDescription: 'Hooks, context, suspense, server components.', proficiency: 5, category: 'Frontend', logo: '/React.svg' },
  { name: 'TypeScript', shortDescription: 'Strict mode, generics, utility types, zod validation.', proficiency: 5, category: 'Language', logo: '/TypeScript.svg' },
  { name: 'Node.js', shortDescription: 'REST APIs, WebSockets, streaming, background jobs.', proficiency: 4, category: 'Backend', logo: '/Node.js.svg' },
  { name: 'Tailwind CSS', shortDescription: 'Custom design systems, responsive layouts, v4 config.', proficiency: 5, category: 'Frontend', logo: '/Tailwind CSS.svg' },
  {name: 'Bootstrap', shortDescription: 'Preprocessors, frameworks, responsive design.', proficiency: 4, category: 'Frontend', logo: '/Bootstrap.svg' },
  {name: 'JavaScript', shortDescription: 'ES6+, async patterns, DOM manipulation, event handling.', proficiency: 5, category: 'Language', logo: '/JavaScript.svg' },
  {name: 'Golang', shortDescription: 'REST APIs with Gin, database interactions with GORM.', proficiency: 3, category: 'Language', logo: '/Go.svg' },
  { name: 'CSS', shortDescription: 'Preprocessors, frameworks, responsive design.', proficiency: 4, category: 'Frontend', logo: '/CSS3.svg' },
  { name: 'PostgreSQL', shortDescription: 'Schema design, query optimisation, migrations with Drizzle.', proficiency: 4, category: 'Database', logo: '/PostgresSQL.svg' },
  { name: 'MongoDB', shortDescription: 'Document modeling, aggregation pipelines, indexing.', proficiency: 3, category: 'Database', logo: '/MongoDB.svg' },
  { name: 'GraphQL', shortDescription: 'Apollo Server, code-gen, persisted queries, DataLoader.', proficiency: 3, category: 'Backend', logo: '/GraphQL.svg' },
  { name: 'Docker', shortDescription: 'Multi-stage builds, Compose, container orchestration basics.', proficiency: 3, category: 'DevOps', logo: '/Docker.svg' },
  { name: 'Figma', shortDescription: 'Component libraries, auto-layout, dev handoff, prototyping.', proficiency: 4, category: 'Design', logo: '/Figma.svg' },
  {name: 'Photoshop', shortDescription: 'Image editing, compositing, optimising assets for web.', proficiency: 3, category: 'Design', logo: '/Adobe Photoshop.svg' },
  { name: 'AWS', shortDescription: 'EC2, S3, Lambda, CloudFront, RDS — production deployments.', proficiency: 3, category: 'DevOps', logo: '/AWS.svg' },
  { name: 'Vercel', shortDescription: 'Serverless deployments, edge functions, performance optimisation.', proficiency: 4, category: 'DevOps', logo: '/Vercel.svg' },
  {name: 'Azure', shortDescription: 'App Services, Blob Storage, Functions, DevOps pipelines.', proficiency: 2, category: 'DevOps', logo: '/Azure.svg' },
  { name: 'Git', shortDescription: 'Branching strategies, rebasing, pull request workflows.', proficiency: 5, category: 'Other', logo: '/Git.svg' },
  {name: 'Swagger', shortDescription: 'API documentation, OpenAPI spec, auto-generated docs.', proficiency: 3, category: 'Other', logo: '/Swagger.svg' },
  {name: 'Postman', shortDescription: 'API testing, environment management, automated test scripts.', proficiency: 4, category: 'Other', logo: '/Postman.svg' },
];
