import { Project, Experience, Contribution, Skill } from './types';

export const projects: Project[] = [
  {
    slug: 'solipay',
    title: 'SoliPay',
    description: 'A full-featured digital banking platform prototype that enables users to manage accounts, simulate transactions, and experience modern financial workflows through a secure and intuitive interface.',
    longDescription: 'SoliPay is a comprehensive digital banking platform prototype designed to simulate modern fintech operations and deliver a seamless user experience for financial management. I led the end-to-end development of the system, building both the frontend and backend architecture to support core banking workflows.\n\nThe platform enables users to perform essential banking operations such as account management, balance tracking, and simulated transactions within a structured and secure environment. It was designed with a strong emphasis on usability, performance, and clarity, reflecting real-world digital banking standards.\n\nOn the frontend, I built a responsive and interactive interface using React.js and TypeScript, ensuring type safety and maintainable component architecture. The backend was developed using Node.js and Express.js, providing a scalable API layer for handling user data, transactions, and financial operations.\n\nMongoDB was used for flexible and efficient data modeling, supporting user accounts, transaction histories, and financial records. I implemented RESTful APIs to enable smooth communication between the frontend and backend, ensuring consistent and real-time data updates across the platform.\n\nKey highlights of the project include secure authentication flows (prototype-level), structured financial data handling, modular architecture, and optimized state management for complex user interactions. The system was designed to mimic real banking experiences while maintaining simplicity for user testing and demonstration purposes.\n\nSoliPay demonstrates my ability to design and build fintech-oriented systems, combining strong backend logic with polished frontend experiences. It reflects my capability to work on complex financial workflows, manage sensitive data structures, and deliver production-quality SaaS-style applications.',
    tags: ['React.js', 'Node.js', 'Express.js', 'MongoDB', 'TypeScript'],
    featured: true,
    liveUrl: 'https://solibank.netlify.app',
    year: '2024',
    images: ['/projects/sp1.png'],
    type: 'web'
  },
  {
    slug: 'beamconnect-lms',
    title: 'Beamconnect LMS',
    description: 'A scalable, multitenant Learning Management System (LMS) designed for organizations and individual learners, enabling interactive learning, course management, and seamless content delivery through a modern web interface.',
    longDescription: 'Beamconnect LMS is a comprehensive, multitenant learning platform built to support both corporate training environments and individual learners through a unified, scalable system. I developed the frontend architecture of the application using Next.js, focusing on performance optimization, modularity, and a highly intuitive user experience.\n\nThe platform enables organizations to onboard users, manage courses, and deliver interactive learning experiences through features such as quizzes, simulations, and collaborative learning tools. It supports multiple tenants within a single system, ensuring secure data separation and customized user experiences for different organizations.\n\nI implemented dynamic data rendering through API integrations using Axios, enabling real-time updates of course content, user progress, and administrative dashboards. The application leverages a combination of Redux and React state management patterns to handle complex workflows involving multiple user roles, including administrators, instructors, and learners.\n\nThe user interface was built with Tailwind CSS, emphasizing responsiveness, accessibility, and clean design across devices. Special attention was given to user journey optimization—from course discovery and enrollment to progress tracking and completion—ensuring a seamless and engaging learning experience.\n\nKey highlights of the project include a modular component architecture for scalability, optimized page performance using Next.js features, secure handling of multi-user data flows, and a design system that supports rapid feature expansion. The platform reflects my ability to build production-ready SaaS applications with complex user interactions, real-time data handling, and enterprise-level usability.\n\nBeamconnect goes beyond traditional learning systems by incorporating interactive and collaborative elements that enhance engagement and knowledge retention, positioning it as a modern solution for digital education and workforce training.',
    tags: ['Next.js', 'JavaScript', 'Axios', 'Redux', 'Tailwind'],
    featured: true,
    liveUrl: 'https://beamconnect.ng',
    year: '2024',
    images: ['/projects/bm1.png', '/projects/bm2.png', '/projects/bm3.png'],
    type: 'web'
  },
  {
    slug: 'tob-africa',
    title: 'tob.Africa',
    description: 'A full-featured event booking platform that enables users to discover, book, and manage events seamlessly through an intuitive and responsive web experience.',
    longDescription: 'tob.Africa is a modern event booking platform designed to simplify how users discover and reserve spots for events across different categories. I designed and developed the platform as a full-stack application, focusing on delivering a smooth and engaging user experience from event discovery to final booking.\n\nThe platform allows event organizers to create and manage events, while users can browse listings, view event details, and complete bookings through a streamlined reservation flow. Emphasis was placed on reducing friction in the booking process, ensuring users can move from discovery to confirmation with minimal steps.\n\nOn the frontend, I built a responsive and intuitive interface using React.js and Tailwind CSS, ensuring accessibility and consistent performance across devices. The backend was developed with Node.js and MongoDB, enabling efficient data storage, retrieval, and management of users, events, and bookings.\n\nI implemented RESTful APIs to handle communication between the frontend and backend, supporting dynamic data rendering for event listings, user interactions, and booking confirmations. The system is structured to handle multiple users concurrently, with a focus on reliability and scalability.\n\nKey highlights of the project include a clean and modular component architecture, optimized booking workflows, real-time data updates, and a user-centric design approach. The platform demonstrates my ability to build end-to-end web applications, integrate frontend and backend systems, and deliver functional products that solve real-world problems in the events and entertainment space.\n\ntob.Africa reflects my capability to combine product thinking with technical execution, creating a platform that is both functional and engaging for users and event organizers alike.',
    tags: ['React.js', 'Node.js', 'MongoDB', 'JavaScript', 'REST APIs', 'Tailwind'],
    liveUrl: 'https://tobafrica.netlify.app',
    year: '2024',
    images: ['/projects/ta1.png'],
    type: 'web'
  },
  {
    slug: 'school-management-system',
    title: 'FASMA APP',
    description: 'A comprehensive full-stack school management platform built to streamline academic and administrative operations for primary and secondary schools through an intuitive and scalable digital system.',
    longDescription: 'FASMA APP is a robust, full-stack school management system designed to digitize and simplify the day-to-day operations of primary and secondary schools. I developed the platform from the ground up, focusing on creating an intuitive system that caters to administrators, teachers, and non-technical staff.\n\nThe application centralizes core school processes, including student enrollment, class and course management, staff administration, and academic reporting. It enables schools to efficiently manage student records, track performance, and organize academic structures within a single unified platform.\n\nOn the frontend, I built a responsive and user-friendly interface using React.js, ensuring that users can easily navigate complex workflows such as student registration, class assignments, and result management. The backend was developed with Node.js and Express.js, providing a structured and scalable API layer for handling business logic and data operations.\n\nMongoDB was used for flexible and efficient data storage, allowing the system to manage diverse data sets such as student profiles, course structures, and academic records. I implemented RESTful APIs to enable seamless communication between the frontend and backend, ensuring real-time data updates and consistent user experiences.\n\nSpecial emphasis was placed on usability and accessibility, given the target users include school staff with varying levels of technical proficiency. The interface was designed to reduce complexity, automate repetitive tasks, and improve operational efficiency across the institution.\n\nKey highlights of the project include a modular and scalable architecture, efficient data handling for large student populations, secure role-based access patterns, and a clean, maintainable codebase. The system demonstrates my ability to build end-to-end solutions that address real-world challenges in the education sector.\n\nFASMA APP reflects my capability to design and deliver production-ready platforms that combine strong backend logic with intuitive frontend experiences, making it a practical and impactful solution for modern school management.',
    tags: ['React.js', 'Node.js', 'Express.js', 'MongoDB', 'JavaScript'],
    liveUrl: 'https://fasmaapp.com',
    year: '2026',
    images: ['/projects/fa1.png', '/projects/fa2.png', '/projects/fa3.png'],
    type: 'web'
  },
  {
    slug: 'access-bank-dividend',
    title: 'Access Bank Dividend Management',
    description: 'A robust multitenant financial web application built for dividend management, enabling institutions to securely manage, process, and monitor shareholder payouts through a scalable and user-friendly interface.',
    longDescription: 'Access Bank Dividend Management is an enterprise-grade, multitenant web application developed to streamline and digitize the management of shareholder dividends across multiple client entities. I was responsible for building the frontend architecture of the platform, focusing on scalability, performance, and a seamless user experience tailored for financial operations.\n\nThe system enables administrators and financial operators to manage dividend records, process payouts, and monitor transaction workflows in real time. It supports multiple tenants within a single platform, ensuring data isolation, secure access control, and customized views per organization.\n\nI implemented dynamic data rendering through seamless API integrations, allowing real-time updates of financial records, transaction histories, and user-specific dashboards. The application leverages advanced state management using Redux to handle complex data flows, ensuring consistency and reliability across different modules.\n\nThe user interface was designed with a strong emphasis on clarity and usability, given the sensitivity and complexity of financial data. I built responsive, intuitive dashboards that simplify navigation across key operations such as dividend allocation, reporting, and account tracking.\n\nKey highlights of the project include optimized data handling for large datasets, modular component architecture, secure frontend patterns, and a highly responsive design system powered by Tailwind CSS. The application demonstrates my ability to build large-scale SaaS financial platforms, work with complex business logic, and deliver production-ready solutions for enterprise clients.',
    tags: ['React.js', 'TypeScript', 'Axios', 'Redux', 'JavaScript', 'Tailwind'],
    liveUrl: 'https://raas.onrender.com',
    year: '2025',
    images: ['/projects/ra1.png', '/projects/ra2.png', '/projects/ra3.png'],
    type: 'web'
  },
  {
    slug: 'letsmeet',
    title: 'Lets Meet',
    description: 'A modern meeting scheduling web application that simplifies how individuals and teams coordinate availability, book meetings, and manage events through shareable links and automated workflows.',
    longDescription: 'Lets Meet is a full-featured meeting scheduling and coordination platform designed to eliminate the friction of back-and-forth communication when planning meetings. I developed the web application using React.js, TypeScript, and Tailwind CSS, focusing on performance, usability, and a clean user experience.\n\nThe platform allows users to create personalized scheduling links, define their availability, and let others book meetings seamlessly. It also supports group scheduling through polling, enabling multiple participants to select preferred time slots, with the system determining the most suitable option.\n\nKey features include calendar-based availability management, responsive booking interfaces, real-time interaction flows, and automated scheduling logic. The UI was built with a strong emphasis on accessibility, responsiveness, and intuitive navigation across devices.\n\nThis project highlights my ability to design and build scalable frontend architectures, implement dynamic user flows, and create SaaS-style products that solve real-world coordination problems.',
    tags: ['React.js', 'TypeScript', 'Tailwind'],
    liveUrl: 'https://letsmeet.chat',
    year: '2026',
    images: ['/projects/lm1.png', '/projects/lm2.png', '/projects/lm3.png'],
    type: 'web'
  },
  {
    slug: 'jenksbuy',
    title: 'JenksBuy',
    description: 'A full-stack e-commerce platform that enables users to browse products, manage carts, and complete seamless purchases through an optimized and responsive web experience.',
    longDescription: 'JenksBuy is a full-featured e-commerce application designed to deliver a smooth and efficient online shopping experience from product discovery to checkout. I developed the platform as a complete end-to-end solution, handling both frontend and backend architecture.\n\nThe application allows users to browse a dynamic product catalog, view detailed product information, add items to a cart, and complete purchases through a streamlined checkout process. Emphasis was placed on creating a frictionless user journey, ensuring that customers can move from discovery to purchase with minimal effort.\n\nOn the frontend, I built a responsive and visually clean interface using React.js and Tailwind CSS, ensuring optimal performance across devices. The backend was developed using Node.js and Express.js, providing a structured API layer to manage products, user interactions, and order processing.\n\nMongoDB was used for flexible data storage, supporting product inventories, user data, and order records. I implemented RESTful APIs to enable seamless communication between the frontend and backend, ensuring real-time updates for cart management, product listings, and checkout flows.\n\nKey features include dynamic cart logic, efficient state handling for user interactions, optimized data fetching, and a modular component architecture for scalability. The system is designed to handle multiple users and transactions concurrently while maintaining performance and reliability.\n\nJenksBuy demonstrates my ability to build scalable marketplace solutions, integrate frontend and backend systems, and deliver production-ready applications that solve real-world commerce challenges.',
    tags: ['React.js', 'Node.js', 'Express.js', 'MongoDB', 'JavaScript', 'Tailwind'],
    year: '2023',
    images: ['/projects/jb2.jpg', '/projects/jb3.jpg', '/projects/jb4.jpg',],
    type: 'mobile'
  },
  {
    slug: 'swinkog-homes',
    title: 'Swinkog Homes',
    description: 'A full-stack mobile real estate application that enables users to discover, browse, and manage property listings, supported by a scalable REST API for seamless data operations.',
    longDescription: 'Swinkog Homes is a mobile-first real estate platform designed to simplify property discovery and management for both agents and prospective buyers. I designed and developed the entire solution, including the mobile application using React Native (Expo) and the backend REST API infrastructure.\n\nThe mobile app provides users with an intuitive interface to browse available properties, view detailed listings, and perform searches based on location, pricing, and property features. It is optimized for performance and responsiveness, ensuring a smooth user experience across different mobile devices.\n\nOn the backend, I built a robust API layer using Node.js and Express.js to handle core functionalities such as property listing management, user interactions, and data retrieval. MongoDB was used as the database to efficiently store and manage property data, supporting flexible schemas for various property types and attributes.\n\nThe platform also includes workflows tailored for real estate agents, allowing them to add, update, and manage property listings directly through the system. This dual-sided functionality ensures that both end users and administrators can interact with the platform effectively.\n\nKey highlights of the project include seamless integration between the mobile frontend and backend services, optimized data fetching for real-time property updates, and a scalable architecture capable of supporting growing property inventories and user activity.\n\nSwinkog Homes demonstrates my ability to build cross-platform mobile applications backed by solid API architecture, delivering complete, production-ready solutions in the real estate and marketplace domain.',
    tags: ['React Native', 'Expo', 'Node.js', 'Express.js', 'MongoDB', 'Tailwind'],
    year: '2025',
    images: ['/projects/sk1.jpg', '/projects/sk2.jpg', '/projects/sk3.jpg'],
    type: 'mobile'
  },
  {
    slug: 'lasu-cooperate',
    title: 'LASUSTECH Cooperative Management System',
    description: 'A modern frontend web application built for the Lagos State University of Science and Technology Cooperative Society, enabling members to manage accounts, track financial activities, and interact with cooperative services seamlessly.',
    longDescription: 'The LASUSTECH Cooperative Management System is a web-based platform developed to digitize and streamline the operations of the Lagos State University of Science and Technology Cooperative Society. I was responsible for building the complete frontend application, focusing on delivering a secure, intuitive, and efficient user experience for cooperative members.\n\nThe platform provides members with access to essential financial and administrative features, including account overviews, transaction tracking, contribution management, and interaction with cooperative services. It transforms traditionally manual cooperative processes into a structured digital workflow, improving transparency and operational efficiency.\n\nI developed the interface using React.js and Tailwind CSS, creating a responsive and user-friendly design that simplifies complex financial interactions. The application integrates with backend services through REST APIs using Axios, enabling dynamic data rendering and real-time updates of user account information and transaction records.\n\nSpecial attention was given to usability and clarity, ensuring that users—regardless of technical proficiency—can easily navigate the system, access their financial data, and perform key actions without confusion. The UI architecture was built with reusable components to support scalability and future feature expansion.\n\nKey highlights of the project include efficient API integration, clean state handling for dynamic data flows, modular component design, and a strong emphasis on performance and responsiveness. The platform demonstrates my ability to build fintech-adjacent systems that handle sensitive financial data with clarity and reliability.\n\nThis project reflects my capability to deliver production-ready web applications that improve real-world financial operations while maintaining a high standard of user experience and technical quality.',
    tags: ['React.js', 'JavaScript', 'Tailwind', 'REST APIs', 'Axios'],
    year: '2024',
    // images: ['/projects/'],
    type: 'web'
  },
  {
    slug: 'student-course-registration',
    title: 'Student Course Registration',
    description: 'A mobile application that enables university students to register for courses, manage their academic load, and streamline semester registration processes.',
    longDescription: 'Student Course Registration is a mobile application built to simplify and digitize the course registration process for university students. The app allows students to view available courses, select preferred modules, and complete semester registration through a structured and intuitive mobile interface.\n\nI developed the application using React Native, focusing on creating a smooth and responsive mobile experience across different device sizes. The system is designed to reduce the complexity typically associated with manual course registration processes in universities.\n\nThe application provides students with features such as course browsing, registration submission, and validation of selected courses based on academic requirements. The UI was designed to be simple and accessible, ensuring that students can easily navigate course offerings and complete registration without confusion.\n\nKey highlights of the project include a mobile-first design approach, efficient state handling for selected courses, structured user flows for registration steps, and a scalable architecture that can be extended to support backend integration for real-time course availability and academic validation.\n\nThis project demonstrates my ability to build functional mobile applications using React Native and design user-centric solutions for real-world academic systems.',
    tags: ['React Native', 'JavaScript', 'Mobile App'],
    year: '2025',
    images: ['/projects/ej8.jpg', '/projects/ej1.jpg', '/projects/ej5.jpg'],
    type: 'mobile'
  }
];

export const experiences: Experience[] = [
  {
    slug: 't-global',
    company: 'Tactology Global',
    logo: '/company/tg.png',
    role: 'Frontend Engineer',
    period: 'March 2026 — Present',
    workMode: 'Remote',
    shortDescription: 'Building modern web solutions and delivering user-centric digital experiences for clients across various industries.',
    longDescription: 'Tactology Global is a digital solutions company established in 2020, comprising a dedicated team of on-site and remote members focused on transforming client visions into tangible products. As a Frontend Engineer, I contribute to building scalable, performant web applications while collaborating closely with design and backend teams to deliver polished, production-ready solutions.',
    tech: ['React.js', 'Next.js', 'TypeScript', 'JavaScript', 'GraphQl'],
    highlights: [
      'Develop and maintain responsive, cross-browser-compatible web applications tailored to client requirements',
      'Collaborate with cross-functional teams to translate design mockups into functional, pixel-perfect UI components',
      'Contribute to codebase quality through code reviews, best practices enforcement, and documentation',
    ],
  },
  {
    slug: 'codeweb-project-solutions',
    company: 'Codeweb Project Solutions',
    logo: '/company/cd.jpg',
    role: 'Frontend Software Developer',
    period: 'Sept 2024 — Present',
    workMode: 'Remote',
    shortDescription: 'Designing and building scalable React.js web applications, including a Hospital Management System, with a focus on performance and cross-device compatibility.',
    longDescription: 'Codeweb Project Solutions is a software development firm delivering custom digital solutions across healthcare, education, and enterprise sectors. I design and develop interactive, high-performance web applications — most notably a Hospital Management System — building modular React.js component libraries and integrating RESTful APIs to power dynamic, data-driven interfaces.',
    tech: ['React.js', 'JavaScript', 'TypeScript', 'Axios', 'Context API', 'REST APIs', 'CSS'],
    highlights: [
      'Designed and developed interactive Hospital Management System (HMS) web pages, improving performance and user experience',
      'Built scalable, reusable React.js component libraries enabling modular and maintainable development across projects',
      'Implemented state management with Hooks and Context API, optimising performance in large-scale applications',
      'Conducted rigorous testing and debugging to ensure cross-browser compatibility and seamless multi-device functionality',
    ],
  },
  {
    slug: 'gapplus-limited',
    company: 'GAPPLUS Limited',
    logo: '/company/gp.png',
    role: 'Frontend Developer',
    period: '2025 — 2026',
    workMode: 'Hybrid',
    shortDescription: 'Developed and maintained reusable React.js components for mobile, desktop, and web, with API integration and complex state management.',
    longDescription: 'GAPPLUS Limited is a technology company delivering software solutions across mobile, desktop, and web platforms. I contributed to both simple and complex product features using React.js, built reusable component systems to streamline development, and integrated APIs via Axios to enable dynamic, interactive user experiences.',
    tech: ['React.js', 'JavaScript', 'CSS', 'Axios', 'Hooks', 'Context API'],
    highlights: [
      'Developed and maintained reusable React.js components to streamline development and improve application consistency across platforms',
      'Integrated APIs using Axios to fetch and display data dynamically, improving user interactivity',
      'Implemented state management using Hooks and Context to manage complex application states across components',
      'Delivered features across mobile, desktop, and web targets, ensuring consistent UX on all form factors',
    ],
  },
  {
    slug: 'waitecc',
    company: 'Boakye Digital',
    logo: '/company/bd.png',
    role: 'Web Developer Lead',
    period: 'Jan 2025 — June 2025',
    workMode: 'Remote',
    shortDescription: 'Led frontend development initiatives and mentored junior developers while delivering interactive, client-ready web applications using React.js.',
    longDescription: 'WAITECC is a digital agency focused on delivering client-facing web solutions. As Web Developer Lead, I spearheaded frontend development efforts using React.js, directed the creation of reusable UI component systems, and mentored junior developers — ensuring code quality, scalability, and on-time project delivery.',
    tech: ['React.js', 'JavaScript', 'CSS', 'REST APIs', 'Context API'],
    highlights: [
      'Led frontend development initiatives, designing and delivering user-friendly, interactive web pages that enhanced client satisfaction',
      'Directed the development of reusable UI components, improving project efficiency by reducing code duplication across teams',
      'Integrated APIs for real-time data flow across multiple client platforms',
      'Mentored junior developers and enforced best practices in state management, ensuring robust and scalable application architecture',
    ],
  },
  {
    slug: 'solmojak-limited',
    company: 'Solmojak Limited',
    logo: '/company/sj.png',
    role: 'Front-End Web Developer',
    period: '2020 — 2024',
    workMode: 'Hybrid',
    shortDescription: 'Built and optimised responsive web applications, developed brand identities, and mentored designers across a 4-year tenure.',
    longDescription: 'Solmojak Limited is a digital and creative agency providing web development, brand identity, and SaaS implementation services. Over four years, I wore multiple hats — building responsive web applications, crafting brand identities, mentoring designers, and supporting SaaS rollouts — consistently delivering user-centered solutions for clients across industries.',
    tech: ['React.js', 'JavaScript', 'HTML', 'CSS', 'Figma', 'Adobe XD', 'Adobe Illustrator'],
    highlights: [
      'Built and optimised responsive web applications, ensuring cross-browser compatibility and well-documented, maintainable code',
      'Developed brand identities and creative designs for digital and print materials including logos, brochures, and banners',
      'Mentored designers, guiding them to deliver projects on time and within scope with user-centered design principles',
      'Implemented and supported SaaS solutions, providing technical assistance and monitoring performance for seamless user experiences',
    ],
  },
];

export const contributions: Contribution[] = [
  {
    slug: 'next-contribution',
    project: 'Next.js',
    description: 'Fixed a hydration mismatch bug in the App Router when using dynamic imports with Suspense boundaries.',
    url: 'https://github.com/vercel/next.js/pull/00000',
    type: 'Bug Fix',
    tags: ['Next.js', 'React'],
    year: '2024',
  },
  {
    slug: 'tailwind-docs',
    project: 'Tailwind CSS',
    description: 'Improved the v4 migration guide with clearer examples for custom plugin authoring.',
    url: 'https://github.com/tailwindlabs/tailwindcss.com/pull/00000',
    type: 'Docs',
    tags: ['Tailwind CSS', 'Documentation'],
    year: '2024',
  },
  {
    slug: 'react-hook-form',
    project: 'React Hook Form',
    description: 'Added TypeScript generics support to the useFieldArray hook for strongly-typed nested forms.',
    url: 'https://github.com/react-hook-form/react-hook-form/pull/00000',
    type: 'Feature',
    tags: ['TypeScript', 'React'],
    year: '2023',
  },
  {
    slug: 'radix-ui',
    project: 'Radix UI',
    description: 'Contributed accessibility improvements to the Dialog component — focus trap now respects dynamically added focusable elements.',
    url: 'https://github.com/radix-ui/primitives/pull/00000',
    type: 'Feature',
    tags: ['Accessibility', 'React'],
    year: '2023',
  },
];

export const skills: Skill[] = [
  { name: 'Next.js', shortDescription: 'App Router, SSR, ISR, edge functions, API routes.', proficiency: 5, category: 'Frontend', logo: '/Next.js.svg' },
  { name: 'React', shortDescription: 'Hooks, context, suspense, server components.', proficiency: 5, category: 'Frontend', logo: '/React.svg' },
  { name: 'TypeScript', shortDescription: 'Strict mode, generics, utility types, zod validation.', proficiency: 5, category: 'Language', logo: '/TypeScript.svg' },
  { name: 'Node.js', shortDescription: 'REST APIs, WebSockets, streaming, background jobs.', proficiency: 4, category: 'Backend', logo: '/Node.js.svg' },
  { name: 'Tailwind CSS', shortDescription: 'Custom design systems, responsive layouts, v4 config.', proficiency: 5, category: 'Frontend', logo: '/Tailwind CSS.svg' },
  { name: 'Bootstrap', shortDescription: 'Preprocessors, frameworks, responsive design.', proficiency: 4, category: 'Frontend', logo: '/Bootstrap.svg' },
  { name: 'JavaScript', shortDescription: 'ES6+, async patterns, DOM manipulation, event handling.', proficiency: 5, category: 'Language', logo: '/JavaScript.svg' },
  { name: 'Golang', shortDescription: 'REST APIs with Gin, database interactions with GORM.', proficiency: 3, category: 'Language', logo: '/Go.svg' },
  { name: 'CSS', shortDescription: 'Preprocessors, frameworks, responsive design.', proficiency: 4, category: 'Frontend', logo: '/CSS3.svg' },
  { name: 'PostgreSQL', shortDescription: 'Schema design, query optimisation, migrations with Drizzle.', proficiency: 4, category: 'Database', logo: '/PostgresSQL.svg' },
  { name: 'MongoDB', shortDescription: 'Document modeling, aggregation pipelines, indexing.', proficiency: 3, category: 'Database', logo: '/MongoDB.svg' },
  { name: 'GraphQL', shortDescription: 'Apollo Server, code-gen, persisted queries, DataLoader.', proficiency: 3, category: 'Backend', logo: '/GraphQL.svg' },
  { name: 'Docker', shortDescription: 'Multi-stage builds, Compose, container orchestration basics.', proficiency: 3, category: 'DevOps', logo: '/Docker.svg' },
  { name: 'Figma', shortDescription: 'Component libraries, auto-layout, dev handoff, prototyping.', proficiency: 4, category: 'Design', logo: '/Figma.svg' },
  { name: 'Photoshop', shortDescription: 'Image editing, compositing, optimising assets for web.', proficiency: 3, category: 'Design', logo: '/Adobe Photoshop.svg' },
  { name: 'AWS', shortDescription: 'EC2, S3, Lambda, CloudFront, RDS — production deployments.', proficiency: 3, category: 'DevOps', logo: '/AWS.svg' },
  { name: 'Vercel', shortDescription: 'Serverless deployments, edge functions, performance optimisation.', proficiency: 4, category: 'DevOps', logo: '/Vercel.svg' },
  { name: 'Azure', shortDescription: 'App Services, Blob Storage, Functions, DevOps pipelines.', proficiency: 2, category: 'DevOps', logo: '/Azure.svg' },
  { name: 'Git', shortDescription: 'Branching strategies, rebasing, pull request workflows.', proficiency: 5, category: 'Other', logo: '/Git.svg' },
  { name: 'Swagger', shortDescription: 'API documentation, OpenAPI spec, auto-generated docs.', proficiency: 3, category: 'Other', logo: '/Swagger.svg' },
  { name: 'Postman', shortDescription: 'API testing, environment management, automated test scripts.', proficiency: 4, category: 'Other', logo: '/Postman.svg' },
];
