import { Project, Experience, Contribution, Skill } from './types';

export const projects: Project[] = [
  {
    slug: 'solipay',
    title: 'SoliPay',
    description: 'A comprehensive digital banking platform prototype with full backend and frontend, designed to enhance user financial experiences.',
    longDescription: 'Led the end-to-end development of SoliPay, a prototype for a comprehensive digital banking platform. Built both the backend and frontend prototype, focusing on intuitive financial workflows and enhanced user experience for modern digital banking.',
    tags: ['React.js', 'Node.js', 'Express.js', 'MongoDB', 'TypeScript'],
    featured: true,
    year: '2024',
  },
  {
    slug: 'beamconnect-lms',
    title: 'Beamconnect LMS',
    description: 'A multitenant Learning Management System for companies and individual users, with dynamic data rendering and scalable component architecture.',
    longDescription: 'Developed and implemented the frontend for Beamconnect, a multitenant LMS serving both corporate and individual learners. Built modular React.js components, integrated APIs via Axios for dynamic content rendering, and managed state with Hooks and Context for complex multi-user workflows.',
    tags: ['Next.js', 'JavaScript', 'Axios', 'Redux', 'Tailwind'],
    featured: true,
    year: '2024',
  },
  {
    slug: 'tob-africa',
    title: 'tob.Africa',
    description: 'An innovative online event booking platform facilitating seamless event reservations and user interactions.',
    longDescription: 'Created tob.Africa, a full-featured online event booking platform. Focused on streamlined reservation flows, intuitive user interactions, and a clean interface to make event discovery and booking seamless for a wide audience.',
    tags: ['React.js', 'Node.js', 'MongoDB', 'JavaScript', 'REST APIs', 'Tailwind'],
    liveUrl: 'https://tob.africa',
    year: '2024',
  },
  {
    slug: 'jenksbuy',
    title: 'JenksBuy',
    description: 'A full-stack e-commerce application with product listings, cart management, and end-to-end purchasing flows.',
    longDescription: 'Developed a complete e-commerce solution for JenksBuy, handling everything from product catalogue and cart logic to checkout flows. Integrated backend APIs with a responsive React.js frontend for a smooth shopping experience.',
    tags: ['React.js', 'Node.js', 'Express.js', 'MongoDB', 'JavaScript', 'Tailwind'],
    year: '2023',
  },
  {
    slug: 'swinkog-homes',
    title: 'Swinkog Homes',
    description: 'A mobile application and REST API suite for a property and real estate outlet, enabling property browsing and management.',
    longDescription: 'Designed and developed both the mobile application (using React Native with Expo) and the backend APIs for Swinkog Homes, a property and real estate platform. Delivered features for property listings, search, and management workflows tailored for agents and end users.',
    tags: ['React Native', 'Expo', 'Node.js', 'Express.js', 'MongoDB', 'Tailwind'],
    year: '2023',
  },
  {
    slug: 'access-bank-dividend',
    title: 'Access Bank Dividend Management',
    description: 'A multitenant frontend web application for dividend management, built for Access Bank.',
    longDescription: 'Developed the frontend web application for a multitenant dividend management system used by Access Bank. Implemented complex state management, dynamic data rendering via integrated APIs, and ensured a polished, user-friendly interface for financial operations at scale.',
    tags: ['React.js', 'TypeScript', 'Axios', 'Redux', 'JavaScript', 'Tailwind'],
    year: '2023',
  },
  {
    slug: 'lasu-cooperate',
    title: 'LASUSTECH Cooperative Society',
    description: 'A frontend web application for the Lagos State University of Science and Technology Cooperative Society.',
    longDescription: 'Built the complete frontend web application for the LASUSTECH Cooperative Society, providing members with an intuitive interface for cooperative management, account activities, and financial services.',
    tags: ['React.js', 'JavaScript', 'Tailwind', 'REST APIs', 'Axios'],
    year: '2023',
  },
  {
    slug: 'school-management-system',
    title: 'School Management System',
    description: 'A full-stack school management platform designed for primary and high schools, covering administration, students, and courses.',
    longDescription: 'Built a comprehensive school management system from the ground up, covering student enrollment, course management, staff administration, and reporting. Designed for use across primary and secondary schools with a focus on ease of use for non-technical staff.',
    tags: ['React.js', 'Node.js', 'Express.js', 'MongoDB', 'JavaScript'],
    year: '2022',
  },
];

export const experiences: Experience[] = [
  {
    slug: 't-global',
    company: 'Tactology Global',
    logo: '/company/tg.png',
    role: 'Frontend Engineer',
    period: 'March 2026 — Present',
    workMode: 'Remote',
    shortDescription: 'Building modern web solutions and delivering user-centric digital experiences for clients across various industries.',
    longDescription: 'Tactology Global is a digital solutions company established in 2020, comprising a dedicated team of on-site and remote members focused on transforming client visions into tangible products. As a Frontend Engineer, I contribute to building scalable, performant web applications while collaborating closely with design and backend teams to deliver polished, production-ready solutions.',
    tech: ['React.js', 'Next.js', 'TypeScript', 'JavaScript', 'GraphQl'],
    highlights: [
      'Develop and maintain responsive, cross-browser-compatible web applications tailored to client requirements',
      'Collaborate with cross-functional teams to translate design mockups into functional, pixel-perfect UI components',
      'Contribute to codebase quality through code reviews, best practices enforcement, and documentation',
    ],
  },
  {
    slug: 'codeweb-project-solutions',
    company: 'Codeweb Project Solutions',
    logo: '/company/cd.jpg',
    role: 'Frontend Software Developer',
    period: 'Sept 2024 — Present',
    workMode: 'Remote',
    shortDescription: 'Designing and building scalable React.js web applications, including a Hospital Management System, with a focus on performance and cross-device compatibility.',
    longDescription: 'Codeweb Project Solutions is a software development firm delivering custom digital solutions across healthcare, education, and enterprise sectors. I design and develop interactive, high-performance web applications — most notably a Hospital Management System — building modular React.js component libraries and integrating RESTful APIs to power dynamic, data-driven interfaces.',
    tech: ['React.js', 'JavaScript', 'TypeScript', 'Axios', 'Context API', 'REST APIs', 'CSS'],
    highlights: [
      'Designed and developed interactive Hospital Management System (HMS) web pages, improving performance and user experience',
      'Built scalable, reusable React.js component libraries enabling modular and maintainable development across projects',
      'Implemented state management with Hooks and Context API, optimising performance in large-scale applications',
      'Conducted rigorous testing and debugging to ensure cross-browser compatibility and seamless multi-device functionality',
    ],
  },
  {
    slug: 'gapplus-limited',
    company: 'GAPPLUS Limited',
    logo: '/company/gp.png',
    role: 'Frontend Developer',
    period: '2025 — 2026',
    workMode: 'Hybrid',
    shortDescription: 'Developed and maintained reusable React.js components for mobile, desktop, and web, with API integration and complex state management.',
    longDescription: 'GAPPLUS Limited is a technology company delivering software solutions across mobile, desktop, and web platforms. I contributed to both simple and complex product features using React.js, built reusable component systems to streamline development, and integrated APIs via Axios to enable dynamic, interactive user experiences.',
    tech: ['React.js', 'JavaScript', 'CSS', 'Axios', 'Hooks', 'Context API'],
    highlights: [
      'Developed and maintained reusable React.js components to streamline development and improve application consistency across platforms',
      'Integrated APIs using Axios to fetch and display data dynamically, improving user interactivity',
      'Implemented state management using Hooks and Context to manage complex application states across components',
      'Delivered features across mobile, desktop, and web targets, ensuring consistent UX on all form factors',
    ],
  },
  {
    slug: 'waitecc',
    company: 'Boakye Digital',
    logo: '/company/bd.png',
    role: 'Web Developer Lead',
    period: 'Jan 2025 — June 2025',
    workMode: 'Remote',
    shortDescription: 'Led frontend development initiatives and mentored junior developers while delivering interactive, client-ready web applications using React.js.',
    longDescription: 'WAITECC is a digital agency focused on delivering client-facing web solutions. As Web Developer Lead, I spearheaded frontend development efforts using React.js, directed the creation of reusable UI component systems, and mentored junior developers — ensuring code quality, scalability, and on-time project delivery.',
    tech: ['React.js', 'JavaScript', 'CSS', 'REST APIs', 'Context API'],
    highlights: [
      'Led frontend development initiatives, designing and delivering user-friendly, interactive web pages that enhanced client satisfaction',
      'Directed the development of reusable UI components, improving project efficiency by reducing code duplication across teams',
      'Integrated APIs for real-time data flow across multiple client platforms',
      'Mentored junior developers and enforced best practices in state management, ensuring robust and scalable application architecture',
    ],
  },
  {
    slug: 'solmojak-limited',
    company: 'Solmojak Limited',
    logo: '/company/sj.png',
    role: 'Front-End Web Developer',
    period: '2020 — 2024',
    workMode: 'Hybrid',
    shortDescription: 'Built and optimised responsive web applications, developed brand identities, and mentored designers across a 4-year tenure.',
    longDescription: 'Solmojak Limited is a digital and creative agency providing web development, brand identity, and SaaS implementation services. Over four years, I wore multiple hats — building responsive web applications, crafting brand identities, mentoring designers, and supporting SaaS rollouts — consistently delivering user-centered solutions for clients across industries.',
    tech: ['React.js', 'JavaScript', 'HTML', 'CSS', 'Figma', 'Adobe XD', 'Adobe Illustrator'],
    highlights: [
      'Built and optimised responsive web applications, ensuring cross-browser compatibility and well-documented, maintainable code',
      'Developed brand identities and creative designs for digital and print materials including logos, brochures, and banners',
      'Mentored designers, guiding them to deliver projects on time and within scope with user-centered design principles',
      'Implemented and supported SaaS solutions, providing technical assistance and monitoring performance for seamless user experiences',
    ],
  },
];

export const contributions: Contribution[] = [
  {
    slug: 'next-contribution',
    project: 'Next.js',
    description: 'Fixed a hydration mismatch bug in the App Router when using dynamic imports with Suspense boundaries.',
    url: 'https://github.com/vercel/next.js/pull/00000',
    type: 'Bug Fix',
    tags: ['Next.js', 'React'],
    year: '2024',
  },
  {
    slug: 'tailwind-docs',
    project: 'Tailwind CSS',
    description: 'Improved the v4 migration guide with clearer examples for custom plugin authoring.',
    url: 'https://github.com/tailwindlabs/tailwindcss.com/pull/00000',
    type: 'Docs',
    tags: ['Tailwind CSS', 'Documentation'],
    year: '2024',
  },
  {
    slug: 'react-hook-form',
    project: 'React Hook Form',
    description: 'Added TypeScript generics support to the useFieldArray hook for strongly-typed nested forms.',
    url: 'https://github.com/react-hook-form/react-hook-form/pull/00000',
    type: 'Feature',
    tags: ['TypeScript', 'React'],
    year: '2023',
  },
  {
    slug: 'radix-ui',
    project: 'Radix UI',
    description: 'Contributed accessibility improvements to the Dialog component — focus trap now respects dynamically added focusable elements.',
    url: 'https://github.com/radix-ui/primitives/pull/00000',
    type: 'Feature',
    tags: ['Accessibility', 'React'],
    year: '2023',
  },
];

export const skills: Skill[] = [
  { name: 'Next.js', shortDescription: 'App Router, SSR, ISR, edge functions, API routes.', proficiency: 5, category: 'Frontend', logo: '/Next.js.svg' },
  { name: 'React', shortDescription: 'Hooks, context, suspense, server components.', proficiency: 5, category: 'Frontend', logo: '/React.svg' },
  { name: 'TypeScript', shortDescription: 'Strict mode, generics, utility types, zod validation.', proficiency: 5, category: 'Language', logo: '/TypeScript.svg' },
  { name: 'Node.js', shortDescription: 'REST APIs, WebSockets, streaming, background jobs.', proficiency: 4, category: 'Backend', logo: '/Node.js.svg' },
  { name: 'Tailwind CSS', shortDescription: 'Custom design systems, responsive layouts, v4 config.', proficiency: 5, category: 'Frontend', logo: '/Tailwind CSS.svg' },
  { name: 'Bootstrap', shortDescription: 'Preprocessors, frameworks, responsive design.', proficiency: 4, category: 'Frontend', logo: '/Bootstrap.svg' },
  { name: 'JavaScript', shortDescription: 'ES6+, async patterns, DOM manipulation, event handling.', proficiency: 5, category: 'Language', logo: '/JavaScript.svg' },
  { name: 'Golang', shortDescription: 'REST APIs with Gin, database interactions with GORM.', proficiency: 3, category: 'Language', logo: '/Go.svg' },
  { name: 'CSS', shortDescription: 'Preprocessors, frameworks, responsive design.', proficiency: 4, category: 'Frontend', logo: '/CSS3.svg' },
  { name: 'PostgreSQL', shortDescription: 'Schema design, query optimisation, migrations with Drizzle.', proficiency: 4, category: 'Database', logo: '/PostgresSQL.svg' },
  { name: 'MongoDB', shortDescription: 'Document modeling, aggregation pipelines, indexing.', proficiency: 3, category: 'Database', logo: '/MongoDB.svg' },
  { name: 'GraphQL', shortDescription: 'Apollo Server, code-gen, persisted queries, DataLoader.', proficiency: 3, category: 'Backend', logo: '/GraphQL.svg' },
  { name: 'Docker', shortDescription: 'Multi-stage builds, Compose, container orchestration basics.', proficiency: 3, category: 'DevOps', logo: '/Docker.svg' },
  { name: 'Figma', shortDescription: 'Component libraries, auto-layout, dev handoff, prototyping.', proficiency: 4, category: 'Design', logo: '/Figma.svg' },
  { name: 'Photoshop', shortDescription: 'Image editing, compositing, optimising assets for web.', proficiency: 3, category: 'Design', logo: '/Adobe Photoshop.svg' },
  { name: 'AWS', shortDescription: 'EC2, S3, Lambda, CloudFront, RDS — production deployments.', proficiency: 3, category: 'DevOps', logo: '/AWS.svg' },
  { name: 'Vercel', shortDescription: 'Serverless deployments, edge functions, performance optimisation.', proficiency: 4, category: 'DevOps', logo: '/Vercel.svg' },
  { name: 'Azure', shortDescription: 'App Services, Blob Storage, Functions, DevOps pipelines.', proficiency: 2, category: 'DevOps', logo: '/Azure.svg' },
  { name: 'Git', shortDescription: 'Branching strategies, rebasing, pull request workflows.', proficiency: 5, category: 'Other', logo: '/Git.svg' },
  { name: 'Swagger', shortDescription: 'API documentation, OpenAPI spec, auto-generated docs.', proficiency: 3, category: 'Other', logo: '/Swagger.svg' },
  { name: 'Postman', shortDescription: 'API testing, environment management, automated test scripts.', proficiency: 4, category: 'Other', logo: '/Postman.svg' },
];
